### PR TITLE
Better styling for menu

### LINKED ISSUE #11: Better styling for menu
## Description
The menu is pretty basic right now. For users, it would probably be better if it was styled to be more attractive, or if it was more isolated and featured at the top of the map space, similar to the app-wide menus for most other apps. (See your browser top menu for an example.)

### Update [Required]
- [ ] Provide mockups for potential options
- [ ] Updating the menu bar styling to be more usable and attractive

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by rossoskull**
Fixes #11 

#### Description
Styling for menu items is improved.

#### Screenshots/GIF
ezgif-3-03ff1f9563b9

### CODE REVIEW

**Comment by rossoskull** [comment]
Okay @sunjunkie, please review this PR

**Comment by justKD** [comment]
Looks good to me. Non-invasive changes for a much better effect.

**Comment by rossoskull** [comment]
Any suggestions? @justKD @sunjunkie

**Comment by sunjunkie** [comment]
Looks good.

**Pull request merged**
